# Generated by Django 5.1.4 on 2025-01-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.BooleanField(choices=[(0, '남성'), (1, '여성')])),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=16)),
                ('personality', models.CharField(max_length=32)),
                ('is_theif', models.BooleanField(choices=[(0, '무고한 시민'), (1, '범인')])),
                ('image', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario.scenario')),
            ],
            options={
                'db_table': 'Suspect',
            },
        ),
    ]
