# Generated by Django 5.1.4 on 2025-01-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspect', '0002_alter_suspect_is_deleted_alter_suspect_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='personality',
        ),
        migrations.AddField(
            model_name='suspect',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='suspect',
            name='init_chat',
            field=models.TextField(blank=True),
        ),
    ]
