# Generated by Django 5.1.5 on 2025-01-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspect', '0003_remove_suspect_personality_suspect_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
