"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import json
from pathlib import Path

ADMINS = [
    ('yeochi2000', 'yeochi2000@example.com'),
    ('PGC0419', 'pgc0419@example.com'),
    ('parkwaterdragon', 'parkwaterdragon@example.com'),
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secrets
try:
    with open(BASE_DIR / 'secrets.json') as f:
        secret_data = json.load(f)
except FileNotFoundError:
    secret_data = {}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_data.get('SECRET_KEY', os.getenv('SECRET_KEY', 'fallback-secret-key'))

#Naver Clova API Keys
NAVER_CLIENT_ID = secret_data.get('NAVER_CLIENT_ID', os.getenv('NAVER_CLIENT_ID', 'fallback-client-id'))
NAVER_CLIENT_SECRET = secret_data.get('NAVER_CLIENT_SECRET', os.getenv('NAVER_CLIENT_SECRET', 'fallback-client-secret'))

#Elevenlabs API Keys
ELEVENLABS_API_KEY = secret_data.get('ELEVENLABS_API_KEY', os.getenv('ELEVENLABS_API_KEY', 'fallback-api-key'))
ELEVENLABS_MODEL_ID = secret_data.get('ELEVENLABS_MODEL_ID', os.getenv('ELEVENLABS_MODEL_ID', 'fallback-model-id'))
# VOICE_IDS 설정 (우선순위: secret.json > .env > fallback)
ELEVENLABS_VOICE_ID = secret_data.get('ELEVENLABS_VOICE_ID', {})

# .env에서 VOICE_IDS를 덮어씌움
for task_id in ELEVENLABS_VOICE_ID.keys():
    ELEVENLABS_VOICE_ID[task_id] = os.getenv(f"TASK_{task_id}_VOICE_ID", ELEVENLABS_VOICE_ID[task_id])

#yourproject/settings.py
OPENAI_API_KEY = secret_data.get('OPENAI_API_KEY', os.getenv('OPENAI_API_KEY', 'your-openai-api-key'))

AWS_ACCESS_KEY_ID = secret_data.get('AWS_ACCESS_KEY_ID', os.getenv('AWS_ACCESS_KEY_ID', 'your-aws-access-key-id'))
AWS_SECRET_ACCESS_KEY = secret_data.get('AWS_SECRET_ACCESS_KEY', os.getenv('AWS_SECRET_ACCESS_KEY', 'your-aws-secret-access-key'))
AWS_STORAGE_BUCKET_NAME = secret_data.get('AWS_STORAGE_BUCKET_NAME', os.getenv('AWS_STORAGE_BUCKET_NAME', 'your-storage-bucket'))
AWS_S3_REGION_NAME = secret_data.get('AWS_S3_REGION_NAME', os.getenv('AWS_S3_REGION_NAME', 'your-s3-region-name'))

EC2_KEY = secret_data.get('EC2_KEY', os.getenv('EC2_KEY', 'your-ec2-key'))
EC2_HOST = secret_data.get('EC2_HOST', os.getenv('EC2_HOST', 'your-ec2-host'))
EC2_NAME = secret_data.get('EC2_NAME', os.getenv('EC2_NAME', 'your-ec2-name'))
# S3 Storage settings
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_FILE_OVERWRITE = False  # 같은 이름 파일 덮어쓰기 방지
AWS_QUERYSTRING_AUTH = False  # URL에서 인증 문자열 제외 (퍼블릭 액세스 허용 시)

# Optional: Pre-signed URL을 사용하려면 설정
AWS_DEFAULT_ACL = None

# SECURITY WARNING: don't run with debug turned on in production!
# 일단 True로 유지
DEBUG = True

ALLOWED_HOSTS = ['ailibi.click', 'www.ailibi.click', 'localhost', '127.0.0.1', 'blue-backend', 'green-backend']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_prometheus',
    'rest_framework',
    'drf_yasg',
    'channels',
    'user',
    'scenario',
    'suspect',
    'evidence',
    'llm',
    'chat',
    'stt',
    'tts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

CORS_ALLOWED_ORIGINS = [
    "https://ailibi.click",       # 메인 도메인
    "https://www.ailibi.click",  # www 서브도메인
    "http://localhost:3000",     # 개발 환경의 프론트엔드
    "https://d3muz3cxd0m51v.cloudfront.net",  # CloudFront 도메인
]

CORS_ALLOW_CREDENTIALS = True  # 쿠키 및 인증 정보를 포함한 요청 허용

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
]
CORS_ALLOW_HEADERS = [
    "Authorization",
    "Content-Type",
]

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'static'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "Backend.asgi.application"

WSGI_APPLICATION = 'Backend.wsgi.application'

# Redis 호스트 이름 설정
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')  # 기본값: redis

# Channels 설정
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS_HOST, 6379)],
        },
    },
}

# Redis CACHES 설정
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:6379/0",  # f-string 사용
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Celery 결과 백엔드 설정
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'  # f-string 사용


# RabbitMQ를 브로커로 사용
CELERY_BROKER_URL = 'amqp://guest:guest@rabbitmq:5672//'

# Celery 작업 데이터 직렬화 형식
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'

CSRF_TRUSTED_ORIGINS = [
    'https://ailibi.click',
    'https://www.ailibi.click',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    "https://d3muz3cxd0m51v.cloudfront.net",  # CloudFront 도메인
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = secret_data.get('DATABASES', {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django_prometheus.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'default_db_name'),
        'USER': os.getenv('DB_USER', 'default_db_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'default_password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
})

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#로깅

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler'
        },
        'file': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.FileHandler',
            'filename': 'django.log'
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_true'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html' : True
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'INFO',
            'propagate': True,
        },
        'chat': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'evidence': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'llm': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'scenario': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'stt': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'suspect': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'tts': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'user': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# 만약 STATICFILES_DIRS나 STATIC_ROOT 설정이 있다면 확인
STATICFILES_DIRS = [
    BASE_DIR / "static",
    # 추가적인 경로가 필요하다면 여기에 추가
]

# 정적 파일이 수집되는 디렉토리
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        }
    },
    'DEFAULT_API_URL': 'https://www.ailibi.click/',
    'SCHEMA': 'https',
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_SSL_REDIRECT = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
