# Generated by Django 5.1.4 on 2025-01-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suspect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('init_chat', models.CharField(max_length=1024)),
                ('user_chat', models.CharField(max_length=1024)),
                ('suspect_chat', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suspect.suspect')),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
    ]
