# Generated by Django 5.1.4 on 2025-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='init_chat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='suspect_chat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_chat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
