# Generated by Django 5.1.4 on 2025-01-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_init_chat_alter_chat_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='init_chat',
        ),
    ]
