# Generated by Django 5.1.4 on 2025-01-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('datetime', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
                ('image', models.CharField(max_length=512)),
                ('level', models.IntegerField()),
                ('note', models.CharField(max_length=512)),
                ('is_success', models.BooleanField(default=False)),
                ('count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Scenario',
            },
        ),
    ]
