# Generated by Django 5.1.4 on 2025-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='is_success',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='note',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
